CFLAGS = -Wall -g -std=c++14
LIBS_L=-lgmock_main -lgmock -lgtest_main -lgtest -lpthread -lgtest
LFLAGS = 
INCLUDES += -I./inc
LIBS=-L./lib
ODIR = $(SOURCE_MAIN)/build/obj
cpp = g++

TEST_DIR = ${PWD}

# List of all source files
SRCS := main.cpp blabla.cpp

include Make/*

# Object files defined from source files
_OBJS = $(notdir $(SRCS:.cpp=.o))
OBJS = $(patsubst %,$(ODIR)/%,$(_OBJS))

MAIN = $(SOURCE_MAIN)/build/bin/testMain

.PHONY: depend clean all

all: $(MAIN)

$(MAIN): $(OBJS)
	$(cpp) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS) $(LIBS_L) $(LD_FLAGS)

$(ODIR)/%.o: %.cpp
	${info $< ---- $@}
	$(cpp) $(CFLAGS) $(INCLUDES) -c -o $@ $<
	
clean:
	rm -rf *.o tests
